spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: demo_user
    password: demo_pass_123
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # Mapper XML 文件位置
  type-aliases-package: com.example.demo.app.entity  # 实体类包路径，简化 XML 中的类型引用
  configuration:
    map-underscore-to-camel-case: true  # 数据库下划线字段自动映射为 Java 驼峰属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 语句到控制台

server:
  port: 8080
